### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by Minghehehe** [adipandas/indoor_bot#2]
Hello,

is file 'robot_pose_ekf.launch' missing? when run command
 $ roslaunch indoor_bot cartographer_slam_teleop.launch
this file cannot be find.

**Comment by adipandas** [comment]
Hi @Minghehehe ,

I worked on this a while ago. For the case of SLAM with teleoperation, you should be able to remove ``robot_pose_ekf.launch`` from the file.

Or you can also try patching amcl_localization to it.
I think that ``robot_pose_ekf.launch`` was replaced with ``amcl_localization.launch``.

I am currently busy with other work. I won't be able to fix this bug in the code immediately. I would really appreciate if you could send in a pull request.

Thank you.
