### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by rohithrio** [adipandas/indoor_bot#3]
Hi sir,we are new to this project ,can you please explain me  how to give file path and gazebo path.

**Comment by adipandas** [comment]
I am not sure what  is the exact error you have. I believe you are trying to run Localization example.
Check [launch/amcl_localization.launch](https://github.com/adipandas/indoor_bot/blob/main/launch/amcl_localization.launch).
It has the default arguments. It should make it clear what files are required to run.
